title: GaoXin's Homepage
page-top-title: GaoXin
top-section-bg-text: Be an engineer in cross-disciplinary
home-subtitle: GaoXin&ensp;|&ensp;高昕
copyright-text: '&copy; GaoXin 2023-2025. All Rights Reserved.'
